export type Alignment =
    "N/A"
    | "lawful good"
    | "neutral good"
    | "chaotic good"
    | "lawful neutral"
    | "neutral"
    | "chaotic neutral"
    | "lawful evil"
    | "neutral evil"
    | "chaotic evil"